### ISSUE TITLE
[request] rename sand

### ISSUE THREAD

**Issue by Zygus42** [Alsender/Earthworks#11]
Could you please rename your little sand bits to something other than Sand to save confusion with vanilla minecraft Sand ?  Small Sand, Sand bits, Sand Portions, Sandlets - something ?

**Comment by Alsender** [comment]
you're going to have to convince me as to why this is confusing, as I fail to see how or why.  The item form of sand has such small and specific uses, that I don't see in what cases it would be confused with vanilla minecraft sand.

**Comment by Zygus42** [comment]
You've never had a typed conversation about it ?  Like for example explaining to someone new to the game how the recipes involving Sand work <- see what I did there ?  Which Sand is which ?  Sandwich you might say.  Because it is either (a) confusing or (b) requires a lot of typing to make sure people know which you're talking about and (c) even Minecraft uses Brick and Bricks, although that's caused it's fair share of confusion over the years also.

**Comment by Alsender** [comment]
But again, item sand has 3 very specific uses.  Even if you are explaining recipes to a completely new player, you can just say "disregard the item and only deal with blocks, because you'll hardly run into a case where you need the item." Plus, item and block are fairly easily interchangeable, only requiring a personal 2X2 creating grid to turn the item back into the block. 

I can see that it may cause some momentary confusion between players only using text to chat, however in my opinion, I like just having Sand and Sand for the names. They look less cluttered than Sand and Pile of Sand, and in the end, they're both just names. Sand, by any other name, would be as gritty.
