### ISSUE TITLE
Can't upgrade from mod version 1.2.3 to higher version

### ISSUE THREAD

**Issue by davespavid** [Alsender/Earthworks#22]
I can't upgrade from mod version 1.2.3 to any higher version Launching a world that I used 1.2.3 in with a newer version prompts me with the "missing blocks" warning. Every Earthworks block is listed as being missing from the new version of the mod.

**Comment by Alsender** [comment]
If you look closer at that warning, it should just be saying that slabs are missing, and they're really not. I fixed slabs and how their items work, so that you can place two slabs of the same type in the same block space (like vanilla has it) which makes minecraft think that the previous item form is missing, but I can assure you that all your slabs in world will still be there.
