### ISSUE TITLE
[Could be fixed with Crafttweaker, but defaults matter] Recipie conflict with Thermal Foundation.

### ISSUE THREAD

**Issue by Notawallplan** [Alsender/Earthworks#27]
The hammer recipies from both Thermal foundation and Earthworks conflict with each other.

**Comment by Alsender** [comment]
Unfortunately, with so many mods out there, and especially so many mods that offer some sort of hammer, recipe conflicts like this are going to be impossible to avoid.  And that's why mods like CraftTweaker or [NoMoreRecipeConflicts](https://minecraft.curseforge.com/projects/stimmedcow-nomorerecipeconflict) exist.  When I made that recipe, I knew that there were going to be conflicts... but other than making a menial middle crafting step, or making the recipe conflict with some other type of tool, there's no good solution...
