### ISSUE TITLE
Recipe and uncrafting issues

### ISSUE THREAD

**Issue by Barhandar** [Alsender/Earthworks#3]
Slate recipe will conflict with any flint storage block. Thatch recipe conflicts with Quark's thatch. Additionally, for both of these and reed it would be nice if they could be crafted back into their resources (9 flint, 4 wheat, 4 sugarcane respectively), or in thatch's case, if it could be crafted out of any grain instead of just wheat but didn't have uncrafting (or uncrafted into "hay", unusable as food, but usable for the mod's recipes).

**Comment by Alsender** [comment]
I've got a fix for the Quark issue, just waiting to finish figuring out how configs work before I update the mod. I'll probably change slate's recipe to be more similar to reed and thatch, i.e. a 2x2 recipe instead. I'm not going to add any uncrafting recipes though, because these aren't meant to be storage blocks.
